services:
  - type: web
    name: gm-leaderboard-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://live-chess-leaderboard.vercel.app
    healthCheckPath: /health
